package com.kousenit;

import com.google.genai.Client;
import com.google.genai.types.GenerateContentResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Uses Google's Gemini model to provide literary criticism of generated operas.
 * Uses the Google GenAI SDK directly for text generation.
 */
public class OperaCritic {

    private static final Logger logger = LoggerFactory.getLogger(OperaCritic.class);

    private static final String GEMINI_MODEL = "gemini-2.0-flash";

    private final Client client;

    public OperaCritic() {
        String apiKey = System.getenv("GOOGLEAI_API_KEY");
        if (apiKey == null || apiKey.isBlank()) {
            apiKey = System.getenv("GOOGLE_API_KEY");
        }
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalStateException("GOOGLEAI_API_KEY or GOOGLE_API_KEY environment variable not set");
        }
        this.client = Client.builder().apiKey(apiKey).build();
    }

    /**
     * Generate a critical review of an opera libretto.
     *
     * @param librettoPath Path to the libretto markdown file
     * @param operaTitle   The title of the opera
     * @return The critical review as a string
     */
    public String reviewOpera(Path librettoPath, String operaTitle) throws IOException {
        String librettoContent = Files.readString(librettoPath);

        String prompt = String.format("""
                You are an experienced music critic with a deep knowledge of opera history,
                dramatic structure, and contemporary theater. You write for major publications
                and are known for insightful, balanced criticism that considers both artistic
                merit and audience appeal.

                Write a detailed literary critique of the following libretto, from an opera
                entitled "%s", suitable for a newspaper review or academic journal.

                Consider the following aspects:
                - The originality and creativity of the premise
                - Character development and dramatic arc
                - Quality of the libretto's poetry and language
                - Theatrical effectiveness and staging potential
                - The alternating writing styles of the AI collaborators
                - How well it adheres to or subverts operatic conventions
                - The ending and overall narrative structure

                Please write as a professional opera critic would, with both praise and
                constructive criticism where appropriate.

                Here is the libretto:

                %s
                """, operaTitle, librettoContent);

        logger.info("Generating critique with {}...", GEMINI_MODEL);

        GenerateContentResponse response = client.models.generateContent(GEMINI_MODEL, prompt, null);

        if (response.text() != null) {
            return response.text();
        } else {
            throw new IOException("No text response from Gemini");
        }
    }

    /**
     * Save a critique to a markdown file in the opera's directory.
     */
    public void saveCritique(String critique, Path operaDir, String operaTitle) throws IOException {
        String filename = operaTitle.toLowerCase()
                .replaceAll("[^a-z0-9\\s]", "")
                .replaceAll("\\s+", "_") + "_critique.md";

        Path critiquePath = operaDir.resolve(filename);

        String formattedCritique = String.format("""
                # Critical Review: %s

                *Generated by Google Gemini*

                ---

                %s
                """, operaTitle, critique);

        Files.writeString(critiquePath, formattedCritique);
        logger.info("Critique saved to: {}", critiquePath.getFileName());
    }

    /**
     * Review an opera and save the critique.
     */
    public void reviewAndSave(Path operaDir, String operaTitle) throws IOException {
        Path librettoPath = operaDir.resolve(
                operaTitle.toLowerCase()
                        .replaceAll("[^a-z0-9\\s]", "")
                        .replaceAll("\\s+", "_") + "_complete_libretto.md"
        );

        if (!Files.exists(librettoPath)) {
            throw new IOException("Libretto file not found: " + librettoPath);
        }

        logger.info("Generating critical review with Google Gemini...");
        String critique = reviewOpera(librettoPath, operaTitle);

        logger.info("Critique generated successfully");
        saveCritique(critique, operaDir, operaTitle);
    }
}
